spring:
  application:
    name: kafka-consumer
  kafka:
    consumer:
      group-id: kafka-consumer
      bootstrap-servers: "localhost:9092"
      properties:
        back.off.period: 5000
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: "012345"
    driver-class-name: org.postgresql.Driver
    # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

